import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import MainProvider from "./_AppComponents/Providers/MainProvider";
import Navbar from "./_AppComponents/Navbar/Navbar";
import { loggedUser } from "./_AppComponents/Guard/loggedUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Wallet",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  // const isLoggedUser = await loggedUser();


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <MainProvider>
          {children}
        </MainProvider>
      </body>
    </html>
  );
}
